export const MOCK_PRODUCTS = [
  {
    id: '2',
    name: 'Smart Watch Series 8 with Health Tracking',
    price: 349.5,
    originalPrice: 399.0,
    rating: 4.9,
    reviews: 3820,
    image: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=500&q=80',
    category: 'Electronics',
    badges: ["New Arrival"],
    inStock: true,
    brand: 'Apple',
    colors: ["Black", "White", "Blue"],
    sizes: ["S", "M", "L"],
    description: 'The latest Series 8 smartwatch with advanced health tracking and beautiful retina display.',
  },
  {
    id: 'a1',
    name: 'AirPods Pro (2nd Generation)',
    price: 249.0,
    rating: 4.8,
    reviews: 5120,
    image: 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=500&q=80',
    category: 'Electronics',
    badges: ["Top Selling"],
    inStock: true,
    brand: 'Apple',
    colors: ["White"],
    sizes: ["One Size"],
    description: 'Rich, high-quality audio and voice with active noise cancellation.',
  },
  {
    id: '12',
    name: 'Nike Air Zoom Pegasus 39',
    price: 120.0,
    rating: 4.8,
    reviews: 5400,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&q=80',
    category: 'Fashion',
    badges: ["Top Selling"],
    inStock: true,
    brand: 'Nike',
    colors: ["Red", "Black", "White"],
    sizes: ["8", "9", "10", "11", "12"],
    description: 'Lightweight, durable, and comfortable running shoes.',
  },
  {
    id: 'sm1',
    name: 'Samsung Galaxy S23 Ultra',
    price: 1199.99,
    originalPrice: 1299.99,
    rating: 4.8,
    reviews: 3100,
    image: 'https://images.unsplash.com/photo-1678911820864-e2c567c655d7?w=500&q=80',
    category: 'Electronics',
    badges: ["New Arrival", "Sale"],
    inStock: true,
    brand: 'Samsung',
    colors: ["Black", "Green", "Cream"],
    sizes: ["256GB", "512GB"],
    description: 'Capture the night in low light. Unbelievable performance.',
  },
  {
    id: 'e1',
    name: 'Apple Premium Device 1',
    price: 1839.62,
    rating: 4.9,
    reviews: 4590,
    image: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=500&q=80',
    category: 'Electronics',
    badges: [],
    inStock: true,
    brand: 'Apple',
    colors: ["Black", "White", "Silver"],
    sizes: ["Standard"],
    description: 'High quality premium electronics.',
  },
  {
    id: 'e2',
    name: 'Sony Premium Device 2',
    price: 656.55,
    rating: 4.3,
    reviews: 3329,
    image: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=500&q=80',
    category: 'Electronics',
    badges: [],
    inStock: true,
    brand: 'Sony',
    colors: ["Black", "White", "Silver"],
    sizes: ["Standard"],
    description: 'High quality premium electronics.',
  },
  {
    id: 'e3',
    name: 'Samsung Premium Device 3',
    price: 991.89,
    rating: 4.3,
    reviews: 4098,
    image: 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=500&q=80',
    category: 'Electronics',
    badges: [],
    inStock: true,
    brand: 'Samsung',
    colors: ["Black", "White", "Silver"],
    sizes: ["Standard"],
    description: 'High quality premium electronics.',
  },
  {
    id: 'e4',
    name: 'Samsung Premium Device 4',
    price: 545.31,
    rating: 4.6,
    reviews: 3255,
    image: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=500&q=80',
    category: 'Electronics',
    badges: ["Sale"],
    inStock: true,
    brand: 'Samsung',
    colors: ["Black", "White", "Silver"],
    sizes: ["Standard"],
    description: 'High quality premium electronics.',
  },
  {
    id: 'e5',
    name: 'Apple Premium Device 5',
    price: 1453.11,
    rating: 4.7,
    reviews: 3676,
    image: 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=500&q=80',
    category: 'Electronics',
    badges: [],
    inStock: true,
    brand: 'Apple',
    colors: ["Black", "White", "Silver"],
    sizes: ["Standard"],
    description: 'High quality premium electronics.',
  },
  {
    id: 'e6',
    name: 'Apple Premium Device 6',
    price: 1617.18,
    originalPrice: 2128.49,
    rating: 4.1,
    reviews: 4694,
    image: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=500&q=80',
    category: 'Electronics',
    badges: [],
    inStock: true,
    brand: 'Apple',
    colors: ["Black", "White", "Silver"],
    sizes: ["Standard"],
    description: 'High quality premium electronics.',
  },
  {
    id: 'e7',
    name: 'Sony Premium Device 7',
    price: 834.1,
    rating: 4.4,
    reviews: 476,
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=500&q=80',
    category: 'Electronics',
    badges: [],
    inStock: true,
    brand: 'Sony',
    colors: ["Black", "White", "Silver"],
    sizes: ["Standard"],
    description: 'High quality premium electronics.',
  },
  {
    id: 'e8',
    name: 'Lenovo Premium Device 8',
    price: 1423.99,
    originalPrice: 2016.2,
    rating: 4.8,
    reviews: 4039,
    image: 'https://images.unsplash.com/photo-1678911820864-e2c567c655d7?w=500&q=80',
    category: 'Electronics',
    badges: [],
    inStock: true,
    brand: 'Lenovo',
    colors: ["Black", "White", "Silver"],
    sizes: ["Standard"],
    description: 'High quality premium electronics.',
  },
  {
    id: 'e9',
    name: 'Lenovo Premium Device 9',
    price: 1097.01,
    rating: 4.7,
    reviews: 2534,
    image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=500&q=80',
    category: 'Electronics',
    badges: [],
    inStock: true,
    brand: 'Lenovo',
    colors: ["Black", "White", "Silver"],
    sizes: ["Standard"],
    description: 'High quality premium electronics.',
  },
  {
    id: 'e10',
    name: 'Samsung Premium Device 10',
    price: 1856.6,
    originalPrice: 2260.11,
    rating: 4.6,
    reviews: 3114,
    image: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=500&q=80',
    category: 'Electronics',
    badges: ["Sale"],
    inStock: true,
    brand: 'Samsung',
    colors: ["Black", "White", "Silver"],
    sizes: ["Standard"],
    description: 'High quality premium electronics.',
  },
  {
    id: 'e11',
    name: 'Lenovo Premium Device 11',
    price: 1039.01,
    rating: 4.1,
    reviews: 1356,
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500&q=80',
    category: 'Electronics',
    badges: [],
    inStock: true,
    brand: 'Lenovo',
    colors: ["Black", "White", "Silver"],
    sizes: ["Standard"],
    description: 'High quality premium electronics.',
  },
  {
    id: 'e12',
    name: 'Samsung Premium Device 12',
    price: 537.73,
    rating: 4.1,
    reviews: 2114,
    image: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=500&q=80',
    category: 'Electronics',
    badges: [],
    inStock: true,
    brand: 'Samsung',
    colors: ["Black", "White", "Silver"],
    sizes: ["Standard"],
    description: 'High quality premium electronics.',
  },
  {
    id: 'e13',
    name: 'Lenovo Premium Device 13',
    price: 474.44,
    rating: 4.9,
    reviews: 3700,
    image: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=500&q=80',
    category: 'Electronics',
    badges: ["Sale"],
    inStock: true,
    brand: 'Lenovo',
    colors: ["Black", "White", "Silver"],
    sizes: ["Standard"],
    description: 'High quality premium electronics.',
  },
  {
    id: 'e14',
    name: 'Samsung Premium Device 14',
    price: 1580.23,
    rating: 4.3,
    reviews: 1087,
    image: 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=500&q=80',
    category: 'Electronics',
    badges: [],
    inStock: true,
    brand: 'Samsung',
    colors: ["Black", "White", "Silver"],
    sizes: ["Standard"],
    description: 'High quality premium electronics.',
  },
  {
    id: 'e15',
    name: 'Apple Premium Device 15',
    price: 1296.18,
    originalPrice: 2444.33,
    rating: 5.0,
    reviews: 2776,
    image: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=500&q=80',
    category: 'Electronics',
    badges: [],
    inStock: true,
    brand: 'Apple',
    colors: ["Black", "White", "Silver"],
    sizes: ["Standard"],
    description: 'High quality premium electronics.',
  },
  {
    id: 'f16',
    name: 'Puma Collection Apparel 1',
    price: 84.37,
    originalPrice: 224.0,
    rating: 4.8,
    reviews: 103,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&q=80',
    category: 'Fashion',
    badges: [],
    inStock: true,
    brand: 'Puma',
    colors: ["Red", "Blue", "Black", "White"],
    sizes: ["S", "M", "L", "XL"],
    description: 'Comfortable and stylish fashion wear.',
  },
  {
    id: 'f17',
    name: 'Puma Collection Apparel 2',
    price: 138.19,
    originalPrice: 230.47,
    rating: 4.0,
    reviews: 719,
    image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500&q=80',
    category: 'Fashion',
    badges: [],
    inStock: true,
    brand: 'Puma',
    colors: ["Red", "Blue", "Black", "White"],
    sizes: ["S", "M", "L", "XL"],
    description: 'Comfortable and stylish fashion wear.',
  },
  {
    id: 'f18',
    name: 'Adidas Collection Apparel 3',
    price: 162.42,
    originalPrice: 221.91,
    rating: 4.3,
    reviews: 3614,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&q=80',
    category: 'Fashion',
    badges: [],
    inStock: true,
    brand: 'Adidas',
    colors: ["Red", "Blue", "Black", "White"],
    sizes: ["S", "M", "L", "XL"],
    description: 'Comfortable and stylish fashion wear.',
  },
  {
    id: 'f19',
    name: 'Reebok Collection Apparel 4',
    price: 177.1,
    rating: 4.9,
    reviews: 4357,
    image: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?w=500&q=80',
    category: 'Fashion',
    badges: [],
    inStock: true,
    brand: 'Reebok',
    colors: ["Red", "Blue", "Black", "White"],
    sizes: ["S", "M", "L", "XL"],
    description: 'Comfortable and stylish fashion wear.',
  },
  {
    id: 'f20',
    name: 'Nike Collection Apparel 5',
    price: 198.52,
    rating: 4.2,
    reviews: 3636,
    image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=500&q=80',
    category: 'Fashion',
    badges: ["New Arrival"],
    inStock: true,
    brand: 'Nike',
    colors: ["Red", "Blue", "Black", "White"],
    sizes: ["S", "M", "L", "XL"],
    description: 'Comfortable and stylish fashion wear.',
  },
  {
    id: 'f21',
    name: 'Nike Collection Apparel 6',
    price: 182.91,
    rating: 4.5,
    reviews: 1041,
    image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=500&q=80',
    category: 'Fashion',
    badges: [],
    inStock: true,
    brand: 'Nike',
    colors: ["Red", "Blue", "Black", "White"],
    sizes: ["S", "M", "L", "XL"],
    description: 'Comfortable and stylish fashion wear.',
  },
  {
    id: 'f22',
    name: 'Nike Collection Apparel 7',
    price: 100.13,
    rating: 4.5,
    reviews: 4190,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&q=80',
    category: 'Fashion',
    badges: [],
    inStock: true,
    brand: 'Nike',
    colors: ["Red", "Blue", "Black", "White"],
    sizes: ["S", "M", "L", "XL"],
    description: 'Comfortable and stylish fashion wear.',
  },
  {
    id: 'f23',
    name: 'Puma Collection Apparel 8',
    price: 51.67,
    rating: 4.7,
    reviews: 1126,
    image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500&q=80',
    category: 'Fashion',
    badges: [],
    inStock: true,
    brand: 'Puma',
    colors: ["Red", "Blue", "Black", "White"],
    sizes: ["S", "M", "L", "XL"],
    description: 'Comfortable and stylish fashion wear.',
  },
  {
    id: 'f24',
    name: 'Puma Collection Apparel 9',
    price: 124.74,
    rating: 4.7,
    reviews: 1143,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&q=80',
    category: 'Fashion',
    badges: ["New Arrival"],
    inStock: true,
    brand: 'Puma',
    colors: ["Red", "Blue", "Black", "White"],
    sizes: ["S", "M", "L", "XL"],
    description: 'Comfortable and stylish fashion wear.',
  },
  {
    id: 'f25',
    name: 'Adidas Collection Apparel 10',
    price: 55.21,
    rating: 4.5,
    reviews: 4526,
    image: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?w=500&q=80',
    category: 'Fashion',
    badges: ["New Arrival"],
    inStock: true,
    brand: 'Adidas',
    colors: ["Red", "Blue", "Black", "White"],
    sizes: ["S", "M", "L", "XL"],
    description: 'Comfortable and stylish fashion wear.',
  },
  {
    id: 'f26',
    name: 'Puma Collection Apparel 11',
    price: 130.15,
    rating: 4.8,
    reviews: 4512,
    image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=500&q=80',
    category: 'Fashion',
    badges: [],
    inStock: true,
    brand: 'Puma',
    colors: ["Red", "Blue", "Black", "White"],
    sizes: ["S", "M", "L", "XL"],
    description: 'Comfortable and stylish fashion wear.',
  },
  {
    id: 'f27',
    name: 'Reebok Collection Apparel 12',
    price: 155.52,
    rating: 4.2,
    reviews: 4134,
    image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=500&q=80',
    category: 'Fashion',
    badges: [],
    inStock: true,
    brand: 'Reebok',
    colors: ["Red", "Blue", "Black", "White"],
    sizes: ["S", "M", "L", "XL"],
    description: 'Comfortable and stylish fashion wear.',
  },
  {
    id: 'f28',
    name: 'Adidas Collection Apparel 13',
    price: 119.27,
    originalPrice: 235.05,
    rating: 4.6,
    reviews: 4254,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&q=80',
    category: 'Fashion',
    badges: [],
    inStock: true,
    brand: 'Adidas',
    colors: ["Red", "Blue", "Black", "White"],
    sizes: ["S", "M", "L", "XL"],
    description: 'Comfortable and stylish fashion wear.',
  },
  {
    id: 'f29',
    name: 'Adidas Collection Apparel 14',
    price: 137.3,
    rating: 4.0,
    reviews: 3583,
    image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500&q=80',
    category: 'Fashion',
    badges: [],
    inStock: true,
    brand: 'Adidas',
    colors: ["Red", "Blue", "Black", "White"],
    sizes: ["S", "M", "L", "XL"],
    description: 'Comfortable and stylish fashion wear.',
  },
  {
    id: 'f30',
    name: 'Reebok Collection Apparel 15',
    price: 56.48,
    rating: 4.5,
    reviews: 4958,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&q=80',
    category: 'Fashion',
    badges: [],
    inStock: true,
    brand: 'Reebok',
    colors: ["Red", "Blue", "Black", "White"],
    sizes: ["S", "M", "L", "XL"],
    description: 'Comfortable and stylish fashion wear.',
  },
  {
    id: 'h31',
    name: 'KitchenPro Essential Item 1',
    price: 29.76,
    rating: 5.0,
    reviews: 67,
    image: 'https://images.unsplash.com/photo-1593618998160-e34014e67546?w=500&q=80',
    category: 'Home & Garden',
    badges: [],
    inStock: true,
    brand: 'KitchenPro',
    colors: ["Natural", "White"],
    sizes: ["Standard"],
    description: 'Perfect addition to your home and garden.',
  },
  {
    id: 'h32',
    name: 'GreenLife Essential Item 2',
    price: 21.07,
    originalPrice: 194.5,
    rating: 4.2,
    reviews: 768,
    image: 'https://images.unsplash.com/photo-1593696954577-ab3d39317b97?w=500&q=80',
    category: 'Home & Garden',
    badges: [],
    inStock: true,
    brand: 'GreenLife',
    colors: ["Natural", "White"],
    sizes: ["Standard"],
    description: 'Perfect addition to your home and garden.',
  },
  {
    id: 'h33',
    name: 'HomeGoods Essential Item 3',
    price: 16.65,
    rating: 4.0,
    reviews: 644,
    image: 'https://images.unsplash.com/photo-1616654876611-399eb5a5e3df?w=500&q=80',
    category: 'Home & Garden',
    badges: [],
    inStock: true,
    brand: 'HomeGoods',
    colors: ["Natural", "White"],
    sizes: ["Standard"],
    description: 'Perfect addition to your home and garden.',
  },
  {
    id: 'h34',
    name: 'HomeGoods Essential Item 4',
    price: 114.92,
    rating: 4.5,
    reviews: 1859,
    image: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=500&q=80',
    category: 'Home & Garden',
    badges: [],
    inStock: true,
    brand: 'HomeGoods',
    colors: ["Natural", "White"],
    sizes: ["Standard"],
    description: 'Perfect addition to your home and garden.',
  },
  {
    id: 'h35',
    name: 'GreenLife Essential Item 5',
    price: 17.03,
    originalPrice: 154.51,
    rating: 4.3,
    reviews: 1302,
    image: 'https://images.unsplash.com/photo-1593618998160-e34014e67546?w=500&q=80',
    category: 'Home & Garden',
    badges: [],
    inStock: true,
    brand: 'GreenLife',
    colors: ["Natural", "White"],
    sizes: ["Standard"],
    description: 'Perfect addition to your home and garden.',
  },
  {
    id: 'h36',
    name: 'HomeGoods Essential Item 6',
    price: 19.3,
    rating: 4.1,
    reviews: 916,
    image: 'https://images.unsplash.com/photo-1593696954577-ab3d39317b97?w=500&q=80',
    category: 'Home & Garden',
    badges: [],
    inStock: true,
    brand: 'HomeGoods',
    colors: ["Natural", "White"],
    sizes: ["Standard"],
    description: 'Perfect addition to your home and garden.',
  },
  {
    id: 'h37',
    name: 'LivingStyle Essential Item 7',
    price: 27.25,
    originalPrice: 162.53,
    rating: 4.8,
    reviews: 1267,
    image: 'https://images.unsplash.com/photo-1616654876611-399eb5a5e3df?w=500&q=80',
    category: 'Home & Garden',
    badges: [],
    inStock: true,
    brand: 'LivingStyle',
    colors: ["Natural", "White"],
    sizes: ["Standard"],
    description: 'Perfect addition to your home and garden.',
  },
  {
    id: 'h38',
    name: 'HomeGoods Essential Item 8',
    price: 72.45,
    rating: 4.4,
    reviews: 705,
    image: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=500&q=80',
    category: 'Home & Garden',
    badges: [],
    inStock: true,
    brand: 'HomeGoods',
    colors: ["Natural", "White"],
    sizes: ["Standard"],
    description: 'Perfect addition to your home and garden.',
  },
  {
    id: 'h39',
    name: 'LivingStyle Essential Item 9',
    price: 87.68,
    rating: 4.4,
    reviews: 1891,
    image: 'https://images.unsplash.com/photo-1593618998160-e34014e67546?w=500&q=80',
    category: 'Home & Garden',
    badges: [],
    inStock: true,
    brand: 'LivingStyle',
    colors: ["Natural", "White"],
    sizes: ["Standard"],
    description: 'Perfect addition to your home and garden.',
  },
  {
    id: 'h40',
    name: 'GreenLife Essential Item 10',
    price: 105.19,
    rating: 4.5,
    reviews: 1723,
    image: 'https://images.unsplash.com/photo-1593696954577-ab3d39317b97?w=500&q=80',
    category: 'Home & Garden',
    badges: [],
    inStock: true,
    brand: 'GreenLife',
    colors: ["Natural", "White"],
    sizes: ["Standard"],
    description: 'Perfect addition to your home and garden.',
  },
  {
    id: 'h41',
    name: 'LivingStyle Essential Item 11',
    price: 44.08,
    rating: 4.5,
    reviews: 1519,
    image: 'https://images.unsplash.com/photo-1616654876611-399eb5a5e3df?w=500&q=80',
    category: 'Home & Garden',
    badges: [],
    inStock: true,
    brand: 'LivingStyle',
    colors: ["Natural", "White"],
    sizes: ["Standard"],
    description: 'Perfect addition to your home and garden.',
  },
  {
    id: 'h42',
    name: 'HomeGoods Essential Item 12',
    price: 90.77,
    rating: 4.4,
    reviews: 689,
    image: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=500&q=80',
    category: 'Home & Garden',
    badges: ["Top Selling"],
    inStock: true,
    brand: 'HomeGoods',
    colors: ["Natural", "White"],
    sizes: ["Standard"],
    description: 'Perfect addition to your home and garden.',
  },
  {
    id: 'h43',
    name: 'LivingStyle Essential Item 13',
    price: 135.55,
    originalPrice: 178.94,
    rating: 4.6,
    reviews: 1514,
    image: 'https://images.unsplash.com/photo-1593618998160-e34014e67546?w=500&q=80',
    category: 'Home & Garden',
    badges: [],
    inStock: true,
    brand: 'LivingStyle',
    colors: ["Natural", "White"],
    sizes: ["Standard"],
    description: 'Perfect addition to your home and garden.',
  },
  {
    id: 'h44',
    name: 'KitchenPro Essential Item 14',
    price: 42.68,
    rating: 4.5,
    reviews: 1560,
    image: 'https://images.unsplash.com/photo-1593696954577-ab3d39317b97?w=500&q=80',
    category: 'Home & Garden',
    badges: ["Top Selling"],
    inStock: true,
    brand: 'KitchenPro',
    colors: ["Natural", "White"],
    sizes: ["Standard"],
    description: 'Perfect addition to your home and garden.',
  },
  {
    id: 'h45',
    name: 'KitchenPro Essential Item 15',
    price: 21.69,
    originalPrice: 195.49,
    rating: 4.4,
    reviews: 1588,
    image: 'https://images.unsplash.com/photo-1616654876611-399eb5a5e3df?w=500&q=80',
    category: 'Home & Garden',
    badges: ["Top Selling"],
    inStock: true,
    brand: 'KitchenPro',
    colors: ["Natural", "White"],
    sizes: ["Standard"],
    description: 'Perfect addition to your home and garden.',
  },
  {
    id: 's46',
    name: 'FitGear Athletic Equipment 1',
    price: 185.51,
    rating: 4.9,
    reviews: 2953,
    image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=500&q=80',
    category: 'Sports',
    badges: [],
    inStock: true,
    brand: 'FitGear',
    colors: ["Black", "Neon Green", "Orange"],
    sizes: ["Standard"],
    description: 'Durable and reliable sports equipment.',
  },
  {
    id: 's47',
    name: 'FitGear Athletic Equipment 2',
    price: 182.43,
    originalPrice: 310.85,
    rating: 4.1,
    reviews: 2285,
    image: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=500&q=80',
    category: 'Sports',
    badges: [],
    inStock: true,
    brand: 'FitGear',
    colors: ["Black", "Neon Green", "Orange"],
    sizes: ["Standard"],
    description: 'Durable and reliable sports equipment.',
  },
  {
    id: 's48',
    name: 'Adidas Athletic Equipment 3',
    price: 193.0,
    originalPrice: 394.33,
    rating: 4.5,
    reviews: 2635,
    image: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=500&q=80',
    category: 'Sports',
    badges: [],
    inStock: true,
    brand: 'Adidas',
    colors: ["Black", "Neon Green", "Orange"],
    sizes: ["Standard"],
    description: 'Durable and reliable sports equipment.',
  },
  {
    id: 's49',
    name: 'FitGear Athletic Equipment 4',
    price: 37.05,
    rating: 4.7,
    reviews: 606,
    image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=500&q=80',
    category: 'Sports',
    badges: [],
    inStock: true,
    brand: 'FitGear',
    colors: ["Black", "Neon Green", "Orange"],
    sizes: ["Standard"],
    description: 'Durable and reliable sports equipment.',
  },
  {
    id: 's50',
    name: 'YogaPro Athletic Equipment 5',
    price: 53.32,
    originalPrice: 331.47,
    rating: 4.9,
    reviews: 1362,
    image: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=500&q=80',
    category: 'Sports',
    badges: [],
    inStock: true,
    brand: 'YogaPro',
    colors: ["Black", "Neon Green", "Orange"],
    sizes: ["Standard"],
    description: 'Durable and reliable sports equipment.',
  },
  {
    id: 's51',
    name: 'FitGear Athletic Equipment 6',
    price: 271.48,
    originalPrice: 310.18,
    rating: 4.6,
    reviews: 1587,
    image: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=500&q=80',
    category: 'Sports',
    badges: [],
    inStock: true,
    brand: 'FitGear',
    colors: ["Black", "Neon Green", "Orange"],
    sizes: ["Standard"],
    description: 'Durable and reliable sports equipment.',
  },
  {
    id: 's52',
    name: 'FitGear Athletic Equipment 7',
    price: 232.83,
    rating: 4.6,
    reviews: 2087,
    image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=500&q=80',
    category: 'Sports',
    badges: [],
    inStock: true,
    brand: 'FitGear',
    colors: ["Black", "Neon Green", "Orange"],
    sizes: ["Standard"],
    description: 'Durable and reliable sports equipment.',
  },
  {
    id: 's53',
    name: 'Adidas Athletic Equipment 8',
    price: 128.44,
    originalPrice: 307.36,
    rating: 4.6,
    reviews: 1851,
    image: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=500&q=80',
    category: 'Sports',
    badges: [],
    inStock: true,
    brand: 'Adidas',
    colors: ["Black", "Neon Green", "Orange"],
    sizes: ["Standard"],
    description: 'Durable and reliable sports equipment.',
  },
  {
    id: 's54',
    name: 'Nike Athletic Equipment 9',
    price: 208.21,
    rating: 5.0,
    reviews: 217,
    image: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=500&q=80',
    category: 'Sports',
    badges: ["Free Shipping"],
    inStock: true,
    brand: 'Nike',
    colors: ["Black", "Neon Green", "Orange"],
    sizes: ["Standard"],
    description: 'Durable and reliable sports equipment.',
  },
  {
    id: 's55',
    name: 'FitGear Athletic Equipment 10',
    price: 250.6,
    originalPrice: 325.31,
    rating: 4.9,
    reviews: 2908,
    image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=500&q=80',
    category: 'Sports',
    badges: [],
    inStock: true,
    brand: 'FitGear',
    colors: ["Black", "Neon Green", "Orange"],
    sizes: ["Standard"],
    description: 'Durable and reliable sports equipment.',
  },
  {
    id: 's56',
    name: 'YogaPro Athletic Equipment 11',
    price: 243.01,
    rating: 4.1,
    reviews: 915,
    image: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=500&q=80',
    category: 'Sports',
    badges: ["Free Shipping"],
    inStock: true,
    brand: 'YogaPro',
    colors: ["Black", "Neon Green", "Orange"],
    sizes: ["Standard"],
    description: 'Durable and reliable sports equipment.',
  },
  {
    id: 's57',
    name: 'YogaPro Athletic Equipment 12',
    price: 47.41,
    rating: 4.5,
    reviews: 2028,
    image: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=500&q=80',
    category: 'Sports',
    badges: [],
    inStock: true,
    brand: 'YogaPro',
    colors: ["Black", "Neon Green", "Orange"],
    sizes: ["Standard"],
    description: 'Durable and reliable sports equipment.',
  },
  {
    id: 's58',
    name: 'Nike Athletic Equipment 13',
    price: 83.7,
    rating: 4.9,
    reviews: 2231,
    image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=500&q=80',
    category: 'Sports',
    badges: [],
    inStock: true,
    brand: 'Nike',
    colors: ["Black", "Neon Green", "Orange"],
    sizes: ["Standard"],
    description: 'Durable and reliable sports equipment.',
  },
  {
    id: 's59',
    name: 'YogaPro Athletic Equipment 14',
    price: 85.11,
    originalPrice: 326.47,
    rating: 4.7,
    reviews: 2896,
    image: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=500&q=80',
    category: 'Sports',
    badges: [],
    inStock: true,
    brand: 'YogaPro',
    colors: ["Black", "Neon Green", "Orange"],
    sizes: ["Standard"],
    description: 'Durable and reliable sports equipment.',
  },
  {
    id: 's60',
    name: 'Adidas Athletic Equipment 15',
    price: 46.24,
    rating: 4.4,
    reviews: 2704,
    image: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=500&q=80',
    category: 'Sports',
    badges: [],
    inStock: true,
    brand: 'Adidas',
    colors: ["Black", "Neon Green", "Orange"],
    sizes: ["Standard"],
    description: 'Durable and reliable sports equipment.',
  },
];

export const MOCK_CATEGORIES = [
  { id: 'c1', name: 'Electronics', image: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=300&q=80' },
  { id: 'c2', name: 'Fashion', image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=300&q=80' },
  { id: 'c3', name: 'Home & Garden', image: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=300&q=80' },
  { id: 'c4', name: 'Sports', image: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=300&q=80' },
];
